RoapConnection.sessionId=103;RoapConnection.JsepPeerConnectionConstructor=webkitPeerConnection00;RoapConnection.SessionDescriptionConstructor=SessionDescription;
function RoapConnection(c,a){var b=this;this.peerConnection=new RoapConnection.JsepPeerConnectionConstructor("STUN stun.l.google.com:19302",function(a,c){!1==c&&(b.moreIceComing=!1,b.markActionNeeded());b.iceCandidateCount+=1});this.sessionId=++RoapConnection.sessionId;this.sequenceNumber=0;this.iceStarted=this.actionNeeded=!1;this.moreIceComing=!0;this.iceCandidateCount=0;this.onsignalingmessage=a;this.peerConnection.onopen=function(){if(b.onopen)b.onopen()};this.peerConnection.onaddstream=function(a){if(b.onaddstream)b.onaddstream(a)};
this.peerConnection.onremovestream=function(a){if(b.onremovestream)b.onremovestream(a)};this.onremovestream=this.onaddstream=null;this.state="new";this.markActionNeeded()}
RoapConnection.prototype.processSignalingMessage=function(c){console.log("Activity on conn "+this.sessionId);this.incomingMessage=c=JSON.parse(c);"new"===this.state?"OFFER"===c.messageType?(this.offer_as_string=c.sdp,this.peerConnection.setRemoteDescription(this.peerConnection.SDP_OFFER,new RoapConnection.SessionDescriptionConstructor(c.sdp)),this.state="offer-received",this.markActionNeeded()):this.error("Illegal message for this state: "+c.messageType+" in state "+this.state):"offer-sent"===this.state?
"ANSWER"===c.messageType?(this.peerConnection.setRemoteDescription(this.peerConnection.SDP_ANSWER,new RoapConnection.SessionDescriptionConstructor(c.sdp)),this.sendOK(),this.state="established"):"pr-answer"===c.messageType?this.peerConnection.setRemoteDescription("pr-answer",new RoapConnection.SessionDescriptionConstructor(c.sdp)):"offer"===c.messageType?this.error("Not written yet"):this.error("Illegal message for this state: "+c.messageType+" in state "+this.state):"established"===this.state&&("OFFER"===
c.messageType?(this.peerConnection.setRemoteDescription(this.peerConnection.SDP_OFFER,new RoapConnection.SessionDescriptionConstructor(c.sdp)),this.state="offer-received",this.markActionNeeded()):this.error("Illegal message for this state: "+c.messageType+" in state "+this.state))};RoapConnection.prototype.addStream=function(c){this.peerConnection.addStream(c);this.markActionNeeded()};
RoapConnection.prototype.removeStream=function(c){var a;for(a=0;a<this.peerConnection.localStreams.length;++a)localStreams[a]===c&&(localStreams[a]=null);this.markActionNeeded()};RoapConnection.prototype.close=function(){this.state="closed";this.peerConnection.close()};RoapConnection.prototype.markActionNeeded=function(){this.actionNeeded=!0;var c=this;this.doLater(function(){c.onstablestate()})};RoapConnection.prototype.doLater=function(c){window.setTimeout(c,1)};
RoapConnection.prototype.onstablestate=function(){var c;if(this.actionNeeded){if("new"===this.state||"established"===this.state){c=this.peerConnection.createOffer({has_audio:!0,has_video:!0});if(c.toSdp()!=this.prevOffer){this.peerConnection.setLocalDescription(this.peerConnection.SDP_OFFER,c);this.peerConnection.startIce();this.state="preparing-offer";this.markActionNeeded();return}console.log("Not sending a new offer")}else if("preparing-offer"===this.state){if(this.moreIceComing)return;this.prevOffer=
this.peerConnection.localDescription.toSdp();this.sendMessage("OFFER",this.prevOffer);this.state="offer-sent"}else if("offer-received"===this.state){c=this.peerConnection.createAnswer(this.offer_as_string,{has_audio:!0,has_video:!0});this.peerConnection.setLocalDescription(this.peerConnection.SDP_ANSWER,c);this.state="offer-received-preparing-answer";if(this.iceStarted){this.markActionNeeded();return}console.log((new Date).getTime()+": Starting ICE in responder");this.peerConnection.startIce();this.iceStarted=
!0}else if("offer-received-preparing-answer"===this.state){if(this.moreIceComing)return;c=this.peerConnection.localDescription;this.sendMessage("ANSWER",c.toSdp());this.state="established"}else this.error("Dazed and confused in state "+this.state+", stopping here");this.actionNeeded=!1}};RoapConnection.prototype.sendOK=function(){this.sendMessage("OK")};
RoapConnection.prototype.sendMessage=function(c,a){var b={};b.messageType=c;b.sdp=a;"OFFER"===c?(b.offererSessionId=this.sessionId,b.answererSessionId=this.otherSessionId,b.seq=++this.sequenceNumber,b.tiebreaker=Math.floor(429496723*Math.random()+1)):(b.offererSessionId=this.incomingMessage.offererSessionId,b.answererSessionId=this.sessionId,b.seq=this.incomingMessage.seq);this.onsignalingmessage(JSON.stringify(b))};RoapConnection.prototype.error=function(c){throw"Error in RoapOnJsep: "+c;};(function(c,a){c.version="0.9.6";c.protocol=1;c.transports=[];c.j=[];c.sockets={};c.connect=function(b,d){var e=c.util.parseUri(b),g,f;a&&a.location&&(e.protocol=e.protocol||a.location.protocol.slice(0,-1),e.host=e.host||(a.document?a.document.domain:a.location.hostname),e.port=e.port||a.location.port);g=c.util.uniqueUri(e);var h={host:e.host,secure:"https"==e.protocol,port:e.port||("https"==e.protocol?443:80),query:e.query||""};c.util.merge(h,d);if(h["force new connection"]||!c.sockets[g])f=new c.Socket(h);
!h["force new connection"]&&f&&(c.sockets[g]=f);f=f||c.sockets[g];return f.of(1<e.path.length?e.path:"")}})("object"===typeof module?module.exports:this.io={},this);
(function(c,a){var b=c.util={},d=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,e="source,protocol,authority,userInfo,user,password,host,port,relative,path,directory,file,query,anchor".split(",");b.parseUri=function(a){for(var a=d.exec(a||""),b={},c=14;c--;)b[e[c]]=a[c]||"";return b};b.uniqueUri=function(f){var d=f.protocol,b=f.host,f=f.port;"document"in
a?(b=b||document.domain,f=f||("https"==d&&"https:"!==document.location.protocol?443:document.location.port)):(b=b||"localhost",!f&&"https"==d&&(f=443));return(d||"http")+"://"+b+":"+(f||80)};b.query=function(a,d){var c=b.chunkQuery(a||""),i=[];b.merge(c,b.chunkQuery(d||""));for(var g in c)c.hasOwnProperty(g)&&i.push(g+"="+c[g]);return i.length?"?"+i.join("&"):""};b.chunkQuery=function(a){for(var d={},a=a.split("&"),b=0,c=a.length,g;b<c;++b)g=a[b].split("="),g[0]&&(d[g[0]]=g[1]);return d};var g=!1;
b.load=function(f){if("document"in a&&"complete"===document.readyState||g)return f();b.on(a,"load",f,!1)};b.on=function(a,b,d,c){a.attachEvent?a.attachEvent("on"+b,d):a.addEventListener&&a.addEventListener(b,d,c)};b.request=function(a){if(a&&"undefined"!=typeof XDomainRequest)return new XDomainRequest;if("undefined"!=typeof XMLHttpRequest&&(!a||b.ua.hasCORS))return new XMLHttpRequest;if(!a)try{return new (window[["Active"].concat("Object").join("X")])("Microsoft.XMLHTTP")}catch(d){}return null};"undefined"!=
typeof window&&b.load(function(){g=!0});b.defer=function(a){if(!b.ua.webkit||"undefined"!=typeof importScripts)return a();b.load(function(){setTimeout(a,100)})};b.merge=function(a,d,c,g){var g=g||[],c="undefined"==typeof c?2:c,e;for(e in d)d.hasOwnProperty(e)&&0>b.indexOf(g,e)&&("object"!==typeof a[e]||!c?(a[e]=d[e],g.push(d[e])):b.merge(a[e],d[e],c-1,g));return a};b.mixin=function(a,d){b.merge(a.prototype,d.prototype)};b.inherit=function(a,d){function b(){}b.prototype=d.prototype;a.prototype=new b};
b.isArray=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};b.intersect=function(a,d){for(var c=[],g=a.length>d.length?a:d,e=a.length>d.length?d:a,m=0,r=e.length;m<r;m++)~b.indexOf(g,e[m])&&c.push(e[m]);return c};b.indexOf=function(a,d,b){for(var c=a.length,b=0>b?0>b+c?0:b+c:b||0;b<c&&a[b]!==d;b++);return c<=b?-1:b};b.toArray=function(a){for(var d=[],b=0,c=a.length;b<c;b++)d.push(a[b]);return d};b.ua={};b.ua.hasCORS="undefined"!=typeof XMLHttpRequest&&function(){try{var a=
new XMLHttpRequest}catch(d){return!1}return void 0!=a.withCredentials}();b.ua.webkit="undefined"!=typeof navigator&&/webkit/i.test(navigator.userAgent)})("undefined"!=typeof io?io:module.exports,this);
(function(c,a){function b(){}c.EventEmitter=b;b.prototype.on=function(d,b){this.$events||(this.$events={});this.$events[d]?a.util.isArray(this.$events[d])?this.$events[d].push(b):this.$events[d]=[this.$events[d],b]:this.$events[d]=b;return this};b.prototype.addListener=b.prototype.on;b.prototype.once=function(a,b){function c(){f.removeListener(a,c);b.apply(this,arguments)}var f=this;c.listener=b;this.on(a,c);return this};b.prototype.removeListener=function(b,c){if(this.$events&&this.$events[b]){var g=
this.$events[b];if(a.util.isArray(g)){for(var f=-1,h=0,k=g.length;h<k;h++)if(g[h]===c||g[h].listener&&g[h].listener===c){f=h;break}if(0>f)return this;g.splice(f,1);g.length||delete this.$events[b]}else(g===c||g.listener&&g.listener===c)&&delete this.$events[b]}return this};b.prototype.removeAllListeners=function(a){this.$events&&this.$events[a]&&(this.$events[a]=null);return this};b.prototype.listeners=function(b){this.$events||(this.$events={});this.$events[b]||(this.$events[b]=[]);a.util.isArray(this.$events[b])||
(this.$events[b]=[this.$events[b]]);return this.$events[b]};b.prototype.emit=function(b){if(!this.$events)return!1;var c=this.$events[b];if(!c)return!1;var g=Array.prototype.slice.call(arguments,1);if("function"==typeof c)c.apply(this,g);else if(a.util.isArray(c))for(var c=c.slice(),f=0,h=c.length;f<h;f++)c[f].apply(this,g);else return!1;return!0}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(c,a){function b(a){return 10>a?"0"+a:a}function d(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var b=n[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function e(a,c){var f,g,h,n,o=k,q,p=c[a];p instanceof Date&&(p=isFinite(a.valueOf())?a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"Z":null);"function"===typeof m&&(p=m.call(c,a,
p));switch(typeof p){case "string":return d(p);case "number":return isFinite(p)?""+p:"null";case "boolean":case "null":return""+p;case "object":if(!p)return"null";k+=i;q=[];if("[object Array]"===Object.prototype.toString.apply(p)){n=p.length;for(f=0;f<n;f+=1)q[f]=e(f,p)||"null";h=0===q.length?"[]":k?"[\n"+k+q.join(",\n"+k)+"\n"+o+"]":"["+q.join(",")+"]";k=o;return h}if(m&&"object"===typeof m){n=m.length;for(f=0;f<n;f+=1)"string"===typeof m[f]&&(g=m[f],(h=e(g,p))&&q.push(d(g)+(k?": ":":")+h))}else for(g in p)Object.prototype.hasOwnProperty.call(p,
g)&&(h=e(g,p))&&q.push(d(g)+(k?": ":":")+h);h=0===q.length?"{}":k?"{\n"+k+q.join(",\n"+k)+"\n"+o+"}":"{"+q.join(",")+"}";k=o;return h}}if(a&&a.parse)return c.JSON={parse:a.parse,stringify:a.stringify};var g=c.JSON={},f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,k,i,n={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f",
"\r":"\\r",'"':'\\"',"\\":"\\\\"},m;g.stringify=function(a,b,c){var d;i=k="";if("number"===typeof c)for(d=0;d<c;d+=1)i+=" ";else"string"===typeof c&&(i=c);if((m=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return e("",{"":a})};g.parse=function(a,b){function c(a,d){var f,g,h=a[d];if(h&&"object"===typeof h)for(f in h)Object.prototype.hasOwnProperty.call(h,f)&&(g=c(h,f),void 0!==g?h[f]=g:delete h[f]);return b.call(a,d,h)}var d,a=""+a;f.lastIndex=
0;f.test(a)&&(a=a.replace(f,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),"function"===typeof b?c({"":d},""):d;throw new SyntaxError("JSON.parse");}})("undefined"!=typeof io?io:module.exports,"undefined"!==typeof JSON?JSON:void 0);
(function(c,a){var b=c.parser={},d=b.packets="disconnect,connect,heartbeat,message,json,event,ack,error,noop".split(","),e=b.reasons=["transport not supported","client not handshaken","unauthorized"],g=b.advice=["reconnect"],f=a.JSON,h=a.util.indexOf;b.encodePacket=function(a){var b=h(d,a.type),c=a.id||"",k=a.endpoint||"",s=a.ack,t=null;switch(a.type){case "error":var A=a.reason?h(e,a.reason):"",a=a.advice?h(g,a.advice):"";if(""!==A||""!==a)t=A+(""!==a?"+"+a:"");break;case "message":""!==a.data&&
(t=a.data);break;case "event":t={name:a.name};a.args&&a.args.length&&(t.args=a.args);t=f.stringify(t);break;case "json":t=f.stringify(a.data);break;case "connect":a.qs&&(t=a.qs);break;case "ack":t=a.ackId+(a.args&&a.args.length?"+"+f.stringify(a.args):"")}b=[b,c+("data"==s?"+":""),k];null!==t&&void 0!==t&&b.push(t);return b.join(":")};b.encodePayload=function(a){var b="";if(1==a.length)return a[0];for(var c=0,d=a.length;c<d;c++)b+="\ufffd"+a[c].length+"\ufffd"+a[c];return b};var k=/([^:]+):([0-9]+)?(\+)?:([^:]+)?:?([\s\S]*)?/;
b.decodePacket=function(a){var b=a.match(k);if(!b)return{};var c=b[2]||"",a=b[5]||"",h={type:d[b[1]],endpoint:b[4]||""};c&&(h.id=c,h.ack=b[3]?"data":!0);switch(h.type){case "error":b=a.split("+");h.reason=e[b[0]]||"";h.advice=g[b[1]]||"";break;case "message":h.data=a||"";break;case "event":try{var s=f.parse(a);h.name=s.name;h.args=s.args}catch(t){}h.args=h.args||[];break;case "json":try{h.data=f.parse(a)}catch(A){}break;case "connect":h.qs=a||"";break;case "ack":if(b=a.match(/^([0-9]+)(\+)?(.*)/))if(h.ackId=
b[1],h.args=[],b[3])try{h.args=b[3]?f.parse(b[3]):[]}catch(w){}}return h};b.decodePayload=function(a){if("\ufffd"==a.charAt(0)){for(var c=[],d=1,f="";d<a.length;d++)"\ufffd"==a.charAt(d)?(c.push(b.decodePacket(a.substr(d+1).substr(0,f))),d+=Number(f)+1,f=""):f+=a.charAt(d);return c}return[b.decodePacket(a)]}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(c,a){function b(a,b){this.socket=a;this.sessid=b}c.Transport=b;a.util.mixin(b,a.EventEmitter);b.prototype.onData=function(b){this.clearCloseTimeout();(this.socket.connected||this.socket.connecting||this.socket.reconnecting)&&this.setCloseTimeout();if(""!==b&&(b=a.parser.decodePayload(b))&&b.length)for(var c=0,g=b.length;c<g;c++)this.onPacket(b[c]);return this};b.prototype.onPacket=function(a){this.socket.setHeartbeatTimeout();if("heartbeat"==a.type)return this.onHeartbeat();if("connect"==
a.type&&""==a.endpoint)this.onConnect();"error"==a.type&&"reconnect"==a.advice&&(this.open=!1);this.socket.onPacket(a);return this};b.prototype.setCloseTimeout=function(){if(!this.closeTimeout){var a=this;this.closeTimeout=setTimeout(function(){a.onDisconnect()},this.socket.closeTimeout)}};b.prototype.onDisconnect=function(){this.close&&this.open&&this.close();this.clearTimeouts();this.socket.onDisconnect();return this};b.prototype.onConnect=function(){this.socket.onConnect();return this};b.prototype.clearCloseTimeout=
function(){this.closeTimeout&&(clearTimeout(this.closeTimeout),this.closeTimeout=null)};b.prototype.clearTimeouts=function(){this.clearCloseTimeout();this.reopenTimeout&&clearTimeout(this.reopenTimeout)};b.prototype.packet=function(b){this.send(a.parser.encodePacket(b))};b.prototype.onHeartbeat=function(){this.packet({type:"heartbeat"})};b.prototype.onOpen=function(){this.open=!0;this.clearCloseTimeout();this.socket.onOpen()};b.prototype.onClose=function(){this.open=!1;this.socket.onClose();this.onDisconnect()};
b.prototype.prepareUrl=function(){var b=this.socket.options;return this.scheme()+"://"+b.host+":"+b.port+"/"+b.resource+"/"+a.protocol+"/"+this.name+"/"+this.sessid};b.prototype.ready=function(a,b){b.call(this)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(c,a,b){function d(c){this.options={port:80,secure:!1,document:"document"in b?document:!1,resource:"socket.io",transports:a.transports,"connect timeout":1E4,"try multiple transports":!0,reconnect:!0,"reconnection delay":500,"reconnection limit":Infinity,"reopen delay":3E3,"max reconnection attempts":10,"sync disconnect on unload":!0,"auto connect":!0,"flash policy port":10843};a.util.merge(this.options,c);this.reconnecting=this.connecting=this.open=this.connected=!1;this.namespaces={};this.buffer=
[];this.doBuffer=!1;if(this.options["sync disconnect on unload"]&&(!this.isXDomain()||a.util.ua.hasCORS)){var f=this;a.util.on(b,"unload",function(){f.disconnectSync()},!1)}this.options["auto connect"]&&this.connect()}function e(){}c.Socket=d;a.util.mixin(d,a.EventEmitter);d.prototype.of=function(b){this.namespaces[b]||(this.namespaces[b]=new a.SocketNamespace(this,b),""!==b&&this.namespaces[b].packet({type:"connect"}));return this.namespaces[b]};d.prototype.publish=function(){this.emit.apply(this,
arguments);var a,b;for(b in this.namespaces)this.namespaces.hasOwnProperty(b)&&(a=this.of(b),a.$emit.apply(a,arguments))};d.prototype.handshake=function(b){function c(a){if(a instanceof Error)d.onError(a.message);else b.apply(null,a.split(":"))}var d=this,k=this.options,k=["http"+(k.secure?"s":"")+":/",k.host+":"+k.port,k.resource,a.protocol,a.util.query(this.options.query,"t="+ +new Date)].join("/");if(this.isXDomain()&&!a.util.ua.hasCORS){var i=document.getElementsByTagName("script")[0],n=document.createElement("script");
n.src=k+"&jsonp="+a.j.length;i.parentNode.insertBefore(n,i);a.j.push(function(a){c(a);n.parentNode.removeChild(n)})}else{var m=a.util.request();m.open("GET",k,!0);m.withCredentials=!0;m.onreadystatechange=function(){4==m.readyState&&(m.onreadystatechange=e,200==m.status?c(m.responseText):!d.reconnecting&&d.onError(m.responseText))};m.send(null)}};d.prototype.getTransport=function(b){for(var b=b||this.transports,c=0,d;d=b[c];c++)if(a.Transport[d]&&a.Transport[d].check(this)&&(!this.isXDomain()||a.Transport[d].xdomainCheck()))return new a.Transport[d](this,
this.sessionid);return null};d.prototype.connect=function(b){if(this.connecting)return this;var c=this;this.handshake(function(d,e,i,n){function m(a){c.transport&&c.transport.clearTimeouts();c.transport=c.getTransport(a);if(!c.transport)return c.publish("connect_failed");c.transport.ready(c,function(){c.connecting=!0;c.publish("connecting",c.transport.name);c.transport.open();c.options["connect timeout"]&&(c.connectTimeoutTimer=setTimeout(function(){if(!c.connected&&(c.connecting=!1,c.options["try multiple transports"])){c.remainingTransports||
(c.remainingTransports=c.transports.slice(0));for(var a=c.remainingTransports;0<a.length&&a.splice(0,1)[0]!=c.transport.name;);a.length?m(a):c.publish("connect_failed")}},c.options["connect timeout"]))})}c.sessionid=d;c.closeTimeout=1E3*i;c.heartbeatTimeout=1E3*e;c.transports=n?a.util.intersect(n.split(","),c.options.transports):c.options.transports;c.setHeartbeatTimeout();m(c.transports);c.once("connect",function(){clearTimeout(c.connectTimeoutTimer);b&&"function"==typeof b&&b()})});return this};
d.prototype.setHeartbeatTimeout=function(){clearTimeout(this.heartbeatTimeoutTimer);var a=this;this.heartbeatTimeoutTimer=setTimeout(function(){a.transport.onClose()},this.heartbeatTimeout)};d.prototype.packet=function(a){this.connected&&!this.doBuffer?this.transport.packet(a):this.buffer.push(a);return this};d.prototype.setBuffer=function(a){this.doBuffer=a;!a&&this.connected&&this.buffer.length&&(this.transport.payload(this.buffer),this.buffer=[])};d.prototype.disconnect=function(){if(this.connected||
this.connecting)this.open&&this.of("").packet({type:"disconnect"}),this.onDisconnect("booted");return this};d.prototype.disconnectSync=function(){a.util.request().open("GET",this.resource+"/"+a.protocol+"/"+this.sessionid,!0);this.onDisconnect("booted")};d.prototype.isXDomain=function(){var a=b.location.port||("https:"==b.location.protocol?443:80);return this.options.host!==b.location.hostname||this.options.port!=a};d.prototype.onConnect=function(){this.connected||(this.connected=!0,this.connecting=
!1,this.doBuffer||this.setBuffer(!1),this.emit("connect"))};d.prototype.onOpen=function(){this.open=!0};d.prototype.onClose=function(){this.open=!1;clearTimeout(this.heartbeatTimeoutTimer)};d.prototype.onPacket=function(a){this.of(a.endpoint).onPacket(a)};d.prototype.onError=function(a){if(a&&a.advice&&"reconnect"===a.advice&&(this.connected||this.connecting))this.disconnect(),this.options.reconnect&&this.reconnect();this.publish("error",a&&a.reason?a.reason:a)};d.prototype.onDisconnect=function(a){var b=
this.connected,c=this.connecting;this.open=this.connecting=this.connected=!1;if(b||c)this.transport.close(),this.transport.clearTimeouts(),b&&(this.publish("disconnect",a),"booted"!=a&&this.options.reconnect&&!this.reconnecting&&this.reconnect())};d.prototype.reconnect=function(){function a(){if(c.connected){for(var d in c.namespaces)c.namespaces.hasOwnProperty(d)&&""!==d&&c.namespaces[d].packet({type:"connect"});c.publish("reconnect",c.transport.name,c.reconnectionAttempts)}clearTimeout(c.reconnectionTimer);
c.removeListener("connect_failed",b);c.removeListener("connect",b);c.reconnecting=!1;delete c.reconnectionAttempts;delete c.reconnectionDelay;delete c.reconnectionTimer;delete c.redoTransports;c.options["try multiple transports"]=e}function b(){if(c.reconnecting){if(c.connected)return a();if(c.connecting&&c.reconnecting)return c.reconnectionTimer=setTimeout(b,1E3);c.reconnectionAttempts++>=d?c.redoTransports?(c.publish("reconnect_failed"),a()):(c.on("connect_failed",b),c.options["try multiple transports"]=
!0,c.transport=c.getTransport(),c.redoTransports=!0,c.connect()):(c.reconnectionDelay<n&&(c.reconnectionDelay*=2),c.connect(),c.publish("reconnecting",c.reconnectionDelay,c.reconnectionAttempts),c.reconnectionTimer=setTimeout(b,c.reconnectionDelay))}}this.reconnecting=!0;this.reconnectionAttempts=0;this.reconnectionDelay=this.options["reconnection delay"];var c=this,d=this.options["max reconnection attempts"],e=this.options["try multiple transports"],n=this.options["reconnection limit"];this.options["try multiple transports"]=
!1;this.reconnectionTimer=setTimeout(b,this.reconnectionDelay);this.on("connect",b)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(c,a){function b(a,b){this.socket=a;this.name=b||"";this.flags={};this.json=new d(this,"json");this.ackPackets=0;this.acks={}}function d(a,b){this.namespace=a;this.name=b}c.SocketNamespace=b;a.util.mixin(b,a.EventEmitter);b.prototype.$emit=a.EventEmitter.prototype.emit;b.prototype.of=function(){return this.socket.of.apply(this.socket,arguments)};b.prototype.packet=function(a){a.endpoint=this.name;this.socket.packet(a);this.flags={};return this};b.prototype.send=function(a,b){var c={type:this.flags.json?
"json":"message",data:a};"function"==typeof b&&(c.id=++this.ackPackets,c.ack=!0,this.acks[c.id]=b);return this.packet(c)};b.prototype.emit=function(a){var b=Array.prototype.slice.call(arguments,1),c=b[b.length-1],d={type:"event",name:a};"function"==typeof c&&(d.id=++this.ackPackets,d.ack="data",this.acks[d.id]=c,b=b.slice(0,b.length-1));d.args=b;return this.packet(d)};b.prototype.disconnect=function(){""===this.name?this.socket.disconnect():(this.packet({type:"disconnect"}),this.$emit("disconnect"));
return this};b.prototype.onPacket=function(b){function c(){d.packet({type:"ack",args:a.util.toArray(arguments),ackId:b.id})}var d=this;switch(b.type){case "connect":this.$emit("connect");break;case "disconnect":if(""===this.name)this.socket.onDisconnect(b.reason||"booted");else this.$emit("disconnect",b.reason);break;case "message":case "json":var h=["message",b.data];"data"==b.ack?h.push(c):b.ack&&this.packet({type:"ack",ackId:b.id});this.$emit.apply(this,h);break;case "event":h=[b.name].concat(b.args);
"data"==b.ack&&h.push(c);this.$emit.apply(this,h);break;case "ack":this.acks[b.ackId]&&(this.acks[b.ackId].apply(this,b.args),delete this.acks[b.ackId]);break;case "error":if(b.advice)this.socket.onError(b);else"unauthorized"==b.reason?this.$emit("connect_failed",b.reason):this.$emit("error",b.reason)}};d.prototype.send=function(){this.namespace.flags[this.name]=!0;this.namespace.send.apply(this.namespace,arguments)};d.prototype.emit=function(){this.namespace.flags[this.name]=!0;this.namespace.emit.apply(this.namespace,
arguments)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(c,a,b){function d(b){a.Transport.apply(this,arguments)}c.websocket=d;a.util.inherit(d,a.Transport);d.prototype.name="websocket";d.prototype.open=function(){var c=a.util.query(this.socket.options.query),d=this,f;f||(f=b.MozWebSocket||b.WebSocket);this.websocket=new f(this.prepareUrl()+c);this.websocket.onopen=function(){d.onOpen();d.socket.setBuffer(!1)};this.websocket.onmessage=function(a){d.onData(a.data)};this.websocket.onclose=function(){d.onClose();d.socket.setBuffer(!0)};this.websocket.onerror=
function(a){d.onError(a)};return this};d.prototype.send=function(a){this.websocket.send(a);return this};d.prototype.payload=function(a){for(var b=0,c=a.length;b<c;b++)this.packet(a[b]);return this};d.prototype.close=function(){this.websocket.close();return this};d.prototype.onError=function(a){this.socket.onError(a)};d.prototype.scheme=function(){return this.socket.options.secure?"wss":"ws"};d.check=function(){return"WebSocket"in b&&!("__addTask"in WebSocket)||"MozWebSocket"in b};d.xdomainCheck=function(){return!0};
a.transports.push("websocket")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(c,a){function b(){a.Transport.websocket.apply(this,arguments)}c.flashsocket=b;a.util.inherit(b,a.Transport.websocket);b.prototype.name="flashsocket";b.prototype.open=function(){var b=this,c=arguments;WebSocket.__addTask(function(){a.Transport.websocket.prototype.open.apply(b,c)});return this};b.prototype.send=function(){var b=this,c=arguments;WebSocket.__addTask(function(){a.Transport.websocket.prototype.send.apply(b,c)});return this};b.prototype.close=function(){WebSocket.__tasks.length=
0;a.Transport.websocket.prototype.close.call(this);return this};b.prototype.ready=function(c,e){function g(){var a=c.options,g=a["flash policy port"],i=["http"+(a.secure?"s":"")+":/",a.host+":"+a.port,a.resource,"static/flashsocket","WebSocketMain"+(c.isXDomain()?"Insecure":"")+".swf"];b.loaded||("undefined"===typeof WEB_SOCKET_SWF_LOCATION&&(WEB_SOCKET_SWF_LOCATION=i.join("/")),843!==g&&WebSocket.loadFlashPolicyFile("xmlsocket://"+a.host+":"+g),WebSocket.__initialize(),b.loaded=!0);e.call(f)}var f=
this;if(document.body)return g();a.util.load(g)};b.check=function(){return"undefined"==typeof WebSocket||!("__initialize"in WebSocket)||!swfobject?!1:10<=swfobject.getFlashPlayerVersion().major};b.xdomainCheck=function(){return!0};"undefined"!=typeof window&&(WEB_SOCKET_DISABLE_AUTO_INITIALIZATION=!0);a.transports.push("flashsocket")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports);
if("undefined"!=typeof window)var swfobject=function(){function c(){if(!z){try{var a=l.getElementsByTagName("body")[0].appendChild(l.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}z=!0;for(var a=D.length,c=0;c<a;c++)D[c]()}}function a(a){z?a():D[D.length]=a}function b(a){if(typeof u.addEventListener!=o)u.addEventListener("load",a,!1);else if(typeof l.addEventListener!=o)l.addEventListener("load",a,!1);else if(typeof u.attachEvent!=o)s(u,"onload",a);else if("function"==typeof u.onload){var b=
u.onload;u.onload=function(){b();a()}}else u.onload=a}function d(){var a=l.getElementsByTagName("body")[0],b=l.createElement(q);b.setAttribute("type",p);var c=a.appendChild(b);if(c){var d=0;(function(){if(typeof c.GetVariable!=o){var f=c.GetVariable("$version");f&&(f=f.split(" ")[1].split(","),j.pv=[parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10)])}else if(10>d){d++;setTimeout(arguments.callee,10);return}a.removeChild(b);c=null;e()})()}else e()}function e(){var a=x.length;if(0<a)for(var b=0;b<
a;b++){var c=x[b].id,d=x[b].callbackFn,i={success:!1,id:c};if(0<j.pv[0]){var e=r(c);if(e)if(t(x[b].swfVersion)&&!(j.wk&&312>j.wk))w(c,!0),d&&(i.success=!0,i.ref=g(c),d(i));else if(x[b].expressInstall&&f()){i={};i.data=x[b].expressInstall;i.width=e.getAttribute("width")||"0";i.height=e.getAttribute("height")||"0";e.getAttribute("class")&&(i.styleclass=e.getAttribute("class"));e.getAttribute("align")&&(i.align=e.getAttribute("align"));for(var n={},e=e.getElementsByTagName("param"),m=e.length,l=0;l<
m;l++)"movie"!=e[l].getAttribute("name").toLowerCase()&&(n[e[l].getAttribute("name")]=e[l].getAttribute("value"));h(i,n,c,d)}else k(e),d&&d(i)}else if(w(c,!0),d){if((c=g(c))&&typeof c.SetVariable!=o)i.success=!0,i.ref=c;d(i)}}}function g(a){var b=null;if((a=r(a))&&"OBJECT"==a.nodeName)typeof a.SetVariable!=o?b=a:(a=a.getElementsByTagName(q)[0])&&(b=a);return b}function f(){return!E&&t("6.0.65")&&(j.win||j.mac)&&!(j.wk&&312>j.wk)}function h(a,b,c,d){E=!0;H=d||null;K={success:!1,id:c};var f=r(c);if(f){"OBJECT"==
f.nodeName?(C=i(f),F=null):(C=f,F=c);a.id=M;if(typeof a.width==o||!/%$/.test(a.width)&&310>parseInt(a.width,10))a.width="310";if(typeof a.height==o||!/%$/.test(a.height)&&137>parseInt(a.height,10))a.height="137";l.title=l.title.slice(0,47)+" - Flash Player Installation";d=j.ie&&j.win?["Active"].concat("").join("X"):"PlugIn";d="MMredirectURL="+u.location.toString().replace(/&/g,"%26")+"&MMplayerType="+d+"&MMdoctitle="+l.title;b.flashvars=typeof b.flashvars!=o?b.flashvars+("&"+d):d;j.ie&&j.win&&4!=
f.readyState&&(d=l.createElement("div"),c+="SWFObjectNew",d.setAttribute("id",c),f.parentNode.insertBefore(d,f),f.style.display="none",function(){f.readyState==4?f.parentNode.removeChild(f):setTimeout(arguments.callee,10)}());n(a,b,c)}}function k(a){if(j.ie&&j.win&&4!=a.readyState){var b=l.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(i(a),b);a.style.display="none";(function(){4==a.readyState?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(i(a),
a)}function i(a){var b=l.createElement("div");if(j.win&&j.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(q)[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)!(1==a[d].nodeType&&"PARAM"==a[d].nodeName)&&8!=a[d].nodeType&&b.appendChild(a[d].cloneNode(!0));return b}function n(a,b,c){var d,f=r(c);if(j.wk&&312>j.wk)return d;if(f)if(typeof a.id==o&&(a.id=c),j.ie&&j.win){var h="",i;for(i in a)a[i]!=Object.prototype[i]&&("data"==i.toLowerCase()?b.movie=a[i]:"styleclass"==i.toLowerCase()?h+=
' class="'+a[i]+'"':"classid"!=i.toLowerCase()&&(h+=" "+i+'="'+a[i]+'"'));i="";for(var g in b)b[g]!=Object.prototype[g]&&(i+='<param name="'+g+'" value="'+b[g]+'" />');f.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+h+">"+i+"</object>";G[G.length]=a.id;d=r(a.id)}else{g=l.createElement(q);g.setAttribute("type",p);for(var e in a)a[e]!=Object.prototype[e]&&("styleclass"==e.toLowerCase()?g.setAttribute("class",a[e]):"classid"!=e.toLowerCase()&&g.setAttribute(e,a[e]));for(h in b)b[h]!=
Object.prototype[h]&&"movie"!=h.toLowerCase()&&(a=g,i=h,e=b[h],c=l.createElement("param"),c.setAttribute("name",i),c.setAttribute("value",e),a.appendChild(c));f.parentNode.replaceChild(g,f);d=g}return d}function m(a){var b=r(a);b&&"OBJECT"==b.nodeName&&(j.ie&&j.win?(b.style.display="none",function(){if(4==b.readyState){var c=r(a);if(c){for(var d in c)"function"==typeof c[d]&&(c[d]=null);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):b.parentNode.removeChild(b))}function r(a){var b=
null;try{b=l.getElementById(a)}catch(c){}return b}function s(a,b,c){a.attachEvent(b,c);B[B.length]=[a,b,c]}function t(a){var b=j.pv,a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?!0:!1}function A(a,b,c,d){if(!j.ie||!j.mac){var f=l.getElementsByTagName("head")[0];if(f){c=c&&"string"==typeof c?c:"screen";d&&(I=v=null);if(!v||I!=c)d=l.createElement("style"),d.setAttribute("type","text/css"),
d.setAttribute("media",c),v=f.appendChild(d),j.ie&&j.win&&typeof l.styleSheets!=o&&0<l.styleSheets.length&&(v=l.styleSheets[l.styleSheets.length-1]),I=c;j.ie&&j.win?v&&typeof v.addRule==q&&v.addRule(a,b):v&&typeof l.createTextNode!=o&&v.appendChild(l.createTextNode(a+" {"+b+"}"))}}}function w(a,b){if(N){var c=b?"visible":"hidden";z&&r(a)?r(a).style.visibility=c:A("#"+a,"visibility:"+c)}}function J(a){return null!=/[\\\"<>\.;]/.exec(a)&&typeof encodeURIComponent!=o?encodeURIComponent(a):a}var o="undefined",
q="object",p="application/x-shockwave-flash",M="SWFObjectExprInst",u=window,l=document,y=navigator,O=!1,D=[function(){O?d():e()}],x=[],G=[],B=[],C,F,H,K,z=!1,E=!1,v,I,N=!0,j=function(){var a=typeof l.getElementById!=o&&typeof l.getElementsByTagName!=o&&typeof l.createElement!=o,b=y.userAgent.toLowerCase(),c=y.platform.toLowerCase(),d=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):/mac/.test(b),b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,f=!+"\v1",h=[0,0,0],i=null;
if(typeof y.plugins!=o&&typeof y.plugins["Shockwave Flash"]==q){if((i=y.plugins["Shockwave Flash"].description)&&!(typeof y.mimeTypes!=o&&y.mimeTypes[p]&&!y.mimeTypes[p].enabledPlugin))O=!0,f=!1,i=i.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),h[0]=parseInt(i.replace(/^(.*)\..*$/,"$1"),10),h[1]=parseInt(i.replace(/^.*\.(.*)\s.*$/,"$1"),10),h[2]=/[a-zA-Z]/.test(i)?parseInt(i.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof u[["Active"].concat("Object").join("X")]!=o)try{var g=new (window[["Active"].concat("Object").join("X")])("ShockwaveFlash.ShockwaveFlash");
if(g&&(i=g.GetVariable("$version")))f=!0,i=i.split(" ")[1].split(","),h=[parseInt(i[0],10),parseInt(i[1],10),parseInt(i[2],10)]}catch(e){}return{w3:a,pv:h,wk:b,ie:f,win:d,mac:c}}();(function(){j.w3&&((typeof l.readyState!=o&&"complete"==l.readyState||typeof l.readyState==o&&(l.getElementsByTagName("body")[0]||l.body))&&c(),z||(typeof l.addEventListener!=o&&l.addEventListener("DOMContentLoaded",c,!1),j.ie&&j.win&&(l.attachEvent("onreadystatechange",function(){"complete"==l.readyState&&(l.detachEvent("onreadystatechange",
arguments.callee),c())}),u==top&&function(){if(!z){try{l.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}c()}}()),j.wk&&function(){z||(/loaded|complete/.test(l.readyState)?c():setTimeout(arguments.callee,0))}(),b(c)))})();(function(){j.ie&&j.win&&window.attachEvent("onunload",function(){for(var a=B.length,b=0;b<a;b++)B[b][0].detachEvent(B[b][1],B[b][2]);a=G.length;for(b=0;b<a;b++)m(G[b]);for(var c in j)j[c]=null;j=null;for(var d in swfobject)swfobject[d]=null;swfobject=
null})})();return{registerObject:function(a,b,c,d){if(j.w3&&a&&b){var f={};f.id=a;f.swfVersion=b;f.expressInstall=c;f.callbackFn=d;x[x.length]=f;w(a,!1)}else d&&d({success:!1,id:a})},getObjectById:function(a){if(j.w3)return g(a)},embedSWF:function(b,c,d,i,g,e,k,m,l,p){var r={success:!1,id:c};j.w3&&!(j.wk&&312>j.wk)&&b&&c&&d&&i&&g?(w(c,!1),a(function(){d+="";i+="";var a={};if(l&&typeof l===q)for(var j in l)a[j]=l[j];a.data=b;a.width=d;a.height=i;j={};if(m&&typeof m===q)for(var s in m)j[s]=m[s];if(k&&
typeof k===q)for(var u in k)j.flashvars=typeof j.flashvars!=o?j.flashvars+("&"+u+"="+k[u]):u+"="+k[u];if(t(g))s=n(a,j,c),a.id==c&&w(c,!0),r.success=!0,r.ref=s;else{if(e&&f()){a.data=e;h(a,j,c,p);return}w(c,!0)}p&&p(r)})):p&&p(r)},switchOffAutoHideShow:function(){N=!1},ua:j,getFlashPlayerVersion:function(){return{major:j.pv[0],minor:j.pv[1],release:j.pv[2]}},hasFlashPlayerVersion:t,createSWF:function(a,b,c){if(j.w3)return n(a,b,c)},showExpressInstall:function(a,b,c,d){j.w3&&f()&&h(a,b,c,d)},removeSWF:function(a){j.w3&&
m(a)},createCSS:function(a,b,c,d){j.w3&&A(a,b,c,d)},addDomLoadEvent:a,addLoadEvent:b,getQueryParamValue:function(a){var b=l.location.search||l.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(null==a)return J(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return J(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(E){var a=r(M);a&&C&&(a.parentNode.replaceChild(C,a),F&&(w(F,!0),j.ie&&j.win&&(C.style.display="block")),
H&&H(K));E=!1}}}}();
(function(){if(!("undefined"==typeof window||window.WebSocket)){var c=window.console;if(!c||!c.log||!c.error)c={log:function(){},error:function(){}};swfobject.hasFlashPlayerVersion("10.0.0")?("file:"==location.protocol&&c.error("WARNING: web-socket-js doesn't work in file:///... URL unless you set Flash Security Settings properly. Open the page via Web server i.e. http://..."),WebSocket=function(a,b,c,e,g){var f=this;f.__id=WebSocket.__nextId++;WebSocket.__instances[f.__id]=f;f.readyState=WebSocket.CONNECTING;
f.bufferedAmount=0;f.__events={};b?"string"==typeof b&&(b=[b]):b=[];setTimeout(function(){WebSocket.__addTask(function(){WebSocket.__flash.create(f.__id,a,b,c||null,e||0,g||null)})},0)},WebSocket.prototype.send=function(a){if(this.readyState==WebSocket.CONNECTING)throw"INVALID_STATE_ERR: Web Socket connection has not been established";a=WebSocket.__flash.send(this.__id,encodeURIComponent(a));if(0>a)return!0;this.bufferedAmount+=a;return!1},WebSocket.prototype.close=function(){this.readyState==WebSocket.CLOSED||
this.readyState==WebSocket.CLOSING||(this.readyState=WebSocket.CLOSING,WebSocket.__flash.close(this.__id))},WebSocket.prototype.addEventListener=function(a,b){a in this.__events||(this.__events[a]=[]);this.__events[a].push(b)},WebSocket.prototype.removeEventListener=function(a,b){if(a in this.__events)for(var c=this.__events[a],e=c.length-1;0<=e;--e)if(c[e]===b){c.splice(e,1);break}},WebSocket.prototype.dispatchEvent=function(a){for(var b=this.__events[a.type]||[],c=0;c<b.length;++c)b[c](a);(b=this["on"+
a.type])&&b(a)},WebSocket.prototype.__handleEvent=function(a){"readyState"in a&&(this.readyState=a.readyState);"protocol"in a&&(this.protocol=a.protocol);if("open"==a.type||"error"==a.type)a=this.__createSimpleEvent(a.type);else if("close"==a.type)a=this.__createSimpleEvent("close");else if("message"==a.type)a=this.__createMessageEvent("message",decodeURIComponent(a.message));else throw"unknown event type: "+a.type;this.dispatchEvent(a)},WebSocket.prototype.__createSimpleEvent=function(a){if(document.createEvent&&
window.Event){var b=document.createEvent("Event");b.initEvent(a,!1,!1);return b}return{type:a,bubbles:!1,cancelable:!1}},WebSocket.prototype.__createMessageEvent=function(a,b){if(document.createEvent&&window.MessageEvent&&!window.opera){var c=document.createEvent("MessageEvent");c.initMessageEvent("message",!1,!1,b,null,null,window,null);return c}return{type:a,data:b,bubbles:!1,cancelable:!1}},WebSocket.CONNECTING=0,WebSocket.OPEN=1,WebSocket.CLOSING=2,WebSocket.CLOSED=3,WebSocket.__flash=null,WebSocket.__instances=
{},WebSocket.__tasks=[],WebSocket.__nextId=0,WebSocket.loadFlashPolicyFile=function(a){WebSocket.__addTask(function(){WebSocket.__flash.loadManualPolicyFile(a)})},WebSocket.__initialize=function(){if(!WebSocket.__flash)if(WebSocket.__swfLocation&&(window.WEB_SOCKET_SWF_LOCATION=WebSocket.__swfLocation),window.WEB_SOCKET_SWF_LOCATION){var a=document.createElement("div");a.id="webSocketContainer";a.style.position="absolute";WebSocket.__isFlashLite()?(a.style.left="0px",a.style.top="0px"):(a.style.left=
"-100px",a.style.top="-100px");var b=document.createElement("div");b.id="webSocketFlash";a.appendChild(b);document.body.appendChild(a);swfobject.embedSWF(WEB_SOCKET_SWF_LOCATION,"webSocketFlash","1","1","10.0.0",null,null,{hasPriority:!0,swliveconnect:!0,allowScriptAccess:"always"},null,function(a){a.success||c.error("[WebSocket] swfobject.embedSWF failed")})}else c.error("[WebSocket] set WEB_SOCKET_SWF_LOCATION to location of WebSocketMain.swf")},WebSocket.__onFlashInitialized=function(){setTimeout(function(){WebSocket.__flash=
document.getElementById("webSocketFlash");WebSocket.__flash.setCallerUrl(location.href);WebSocket.__flash.setDebug(!!window.WEB_SOCKET_DEBUG);for(var a=0;a<WebSocket.__tasks.length;++a)WebSocket.__tasks[a]();WebSocket.__tasks=[]},0)},WebSocket.__onFlashEvent=function(){setTimeout(function(){try{for(var a=WebSocket.__flash.receiveEvents(),b=0;b<a.length;++b)WebSocket.__instances[a[b].webSocketId].__handleEvent(a[b])}catch(d){c.error(d)}},0);return!0},WebSocket.__log=function(a){c.log(decodeURIComponent(a))},
WebSocket.__error=function(a){c.error(decodeURIComponent(a))},WebSocket.__addTask=function(a){WebSocket.__flash?a():WebSocket.__tasks.push(a)},WebSocket.__isFlashLite=function(){if(!window.navigator||!window.navigator.mimeTypes)return!1;var a=window.navigator.mimeTypes["application/x-shockwave-flash"];return!a||!a.enabledPlugin||!a.enabledPlugin.filename?!1:a.enabledPlugin.filename.match(/flashlite/i)?!0:!1},window.WEB_SOCKET_DISABLE_AUTO_INITIALIZATION||(window.addEventListener?window.addEventListener("load",
function(){WebSocket.__initialize()},!1):window.attachEvent("onload",function(){WebSocket.__initialize()}))):c.error("Flash Player >= 10.0.0 is required.")}})();
(function(c,a,b){function d(b){b&&(a.Transport.apply(this,arguments),this.sendBuffer=[])}function e(){}c.XHR=d;a.util.inherit(d,a.Transport);d.prototype.open=function(){this.socket.setBuffer(!1);this.onOpen();this.get();this.setCloseTimeout();return this};d.prototype.payload=function(b){for(var c=[],d=0,e=b.length;d<e;d++)c.push(a.parser.encodePacket(b[d]));this.send(a.parser.encodePayload(c))};d.prototype.send=function(a){this.post(a);return this};d.prototype.post=function(a){function c(){if(4==
this.readyState)if(this.onreadystatechange=e,k.posting=!1,200==this.status)k.socket.setBuffer(!1);else k.onClose()}function d(){this.onload=e;k.socket.setBuffer(!1)}var k=this;this.socket.setBuffer(!0);this.sendXHR=this.request("POST");b.XDomainRequest&&this.sendXHR instanceof XDomainRequest?this.sendXHR.onload=this.sendXHR.onerror=d:this.sendXHR.onreadystatechange=c;this.sendXHR.send(a)};d.prototype.close=function(){this.onClose();return this};d.prototype.request=function(b){var c=a.util.request(this.socket.isXDomain()),
d=a.util.query(this.socket.options.query,"t="+ +new Date);c.open(b||"GET",this.prepareUrl()+d,!0);if("POST"==b)try{c.setRequestHeader?c.setRequestHeader("Content-type","text/plain;charset=UTF-8"):c.contentType="text/plain"}catch(e){}return c};d.prototype.scheme=function(){return this.socket.options.secure?"https":"http"};d.check=function(c,d){try{var h=a.util.request(d),e=b.XDomainRequest&&h instanceof XDomainRequest,i=(c&&c.options&&c.options.secure?"https:":"http:")!=b.location.protocol;if(h&&(!e||
!i))return!0}catch(n){}return!1};d.xdomainCheck=function(){return d.check(null,!0)}})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(c,a){function b(b){a.Transport.XHR.apply(this,arguments)}c.htmlfile=b;a.util.inherit(b,a.Transport.XHR);b.prototype.name="htmlfile";b.prototype.get=function(){this.doc=new (window[["Active"].concat("Object").join("X")])("htmlfile");this.doc.open();this.doc.write("<html></html>");this.doc.close();this.doc.parentWindow.s=this;var b=this.doc.createElement("div");b.className="socketio";this.doc.body.appendChild(b);this.iframe=this.doc.createElement("iframe");b.appendChild(this.iframe);var c=
this,b=a.util.query(this.socket.options.query,"t="+ +new Date);this.iframe.src=this.prepareUrl()+b;a.util.on(window,"unload",function(){c.destroy()})};b.prototype._=function(a,b){this.onData(a);try{var c=b.getElementsByTagName("script")[0];c.parentNode.removeChild(c)}catch(f){}};b.prototype.destroy=function(){if(this.iframe){try{this.iframe.src="about:blank"}catch(a){}this.doc=null;this.iframe.parentNode.removeChild(this.iframe);this.iframe=null;CollectGarbage()}};b.prototype.close=function(){this.destroy();
return a.Transport.XHR.prototype.close.call(this)};b.check=function(){if("undefined"!=typeof window&&["Active"].concat("Object").join("X")in window)try{return new (window[["Active"].concat("Object").join("X")])("htmlfile")&&a.Transport.XHR.check()}catch(b){}return!1};b.xdomainCheck=function(){return!1};a.transports.push("htmlfile")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(c,a,b){function d(){a.Transport.XHR.apply(this,arguments)}function e(){}c["xhr-polling"]=d;a.util.inherit(d,a.Transport.XHR);a.util.merge(d,a.Transport.XHR);d.prototype.name="xhr-polling";d.prototype.open=function(){a.Transport.XHR.prototype.open.call(this);return!1};d.prototype.get=function(){function a(){if(4==this.readyState)if(this.onreadystatechange=e,200==this.status)k.onData(this.responseText),k.get();else k.onClose()}function c(){this.onerror=this.onload=e;k.onData(this.responseText);
k.get()}function d(){k.onClose()}if(this.open){var k=this;this.xhr=this.request();b.XDomainRequest&&this.xhr instanceof XDomainRequest?(this.xhr.onload=c,this.xhr.onerror=d):this.xhr.onreadystatechange=a;this.xhr.send(null)}};d.prototype.onClose=function(){a.Transport.XHR.prototype.onClose.call(this);if(this.xhr){this.xhr.onreadystatechange=this.xhr.onload=this.xhr.onerror=e;try{this.xhr.abort()}catch(b){}this.xhr=null}};d.prototype.ready=function(b,c){var d=this;a.util.defer(function(){c.call(d)})};
a.transports.push("xhr-polling")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(c,a,b){function d(b){a.Transport["xhr-polling"].apply(this,arguments);this.index=a.j.length;var c=this;a.j.push(function(a){c._(a)})}var e=b.document&&"MozAppearance"in b.document.documentElement.style;c["jsonp-polling"]=d;a.util.inherit(d,a.Transport["xhr-polling"]);d.prototype.name="jsonp-polling";d.prototype.post=function(b){function c(){d();e.socket.setBuffer(!1)}function d(){e.iframe&&e.form.removeChild(e.iframe);try{s=document.createElement('<iframe name="'+e.iframeId+'">')}catch(a){s=
document.createElement("iframe"),s.name=e.iframeId}s.id=e.iframeId;e.form.appendChild(s);e.iframe=s}var e=this,i=a.util.query(this.socket.options.query,"t="+ +new Date+"&i="+this.index);if(!this.form){var n=document.createElement("form"),m=document.createElement("textarea"),r=this.iframeId="socketio_iframe_"+this.index,s;n.className="socketio";n.style.position="absolute";n.style.top="0px";n.style.left="0px";n.style.display="none";n.target=r;n.method="POST";n.setAttribute("accept-charset","utf-8");
m.name="d";n.appendChild(m);document.body.appendChild(n);this.form=n;this.area=m}this.form.action=this.prepareUrl()+i;d();this.area.value=a.JSON.stringify(b);try{this.form.submit()}catch(t){}this.iframe.attachEvent?s.onreadystatechange=function(){"complete"==e.iframe.readyState&&c()}:this.iframe.onload=c;this.socket.setBuffer(!0)};d.prototype.get=function(){var b=this,c=document.createElement("script"),d=a.util.query(this.socket.options.query,"t="+ +new Date+"&i="+this.index);this.script&&(this.script.parentNode.removeChild(this.script),
this.script=null);c.async=!0;c.src=this.prepareUrl()+d;c.onerror=function(){b.onClose()};d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(c,d);this.script=c;e&&setTimeout(function(){var a=document.createElement("iframe");document.body.appendChild(a);document.body.removeChild(a)},100)};d.prototype._=function(a){this.onData(a);this.open&&this.get();return this};d.prototype.ready=function(b,c){var d=this;if(!e)return c.call(this);a.util.load(function(){c.call(d)})};d.check=function(){return"document"in
b};d.xdomainCheck=function(){return!0};a.transports.push("jsonp-polling")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);var EventDispatcher=function(c){var a={};c.dispatcher={};c.dispatcher.eventListeners={};a.addEventListener=function(a,d){void 0===c.dispatcher.eventListeners[a]&&(c.dispatcher.eventListeners[a]=[]);c.dispatcher.eventListeners[a].push(d)};a.removeEventListener=function(a,d){var e;e=c.dispatcher.eventListeners[a].indexOf(d);-1!==e&&c.dispatcher.eventListeners[a].splice(e,1)};a.dispatchEvent=function(a){var d;L.Logger.debug("Event: "+a.type);for(d in c.dispatcher.eventListeners[a.type])if(c.dispatcher.eventListeners[a.type].hasOwnProperty(d))c.dispatcher.eventListeners[a.type][d](a)};
return a},LynckiaEvent=function(c){var a={};a.type=c.type;return a},RoomEvent=function(c){var a=LynckiaEvent(c);a.streams=c.streams;return a},StreamEvent=function(c){var a=LynckiaEvent(c);a.stream=c.stream;return a},PublisherEvent=function(c){return LynckiaEvent(c)};var Stream=function(c){var a={elementID:void 0};a.streamID=c.streamID;a.stream=c.stream;return a};var Publisher=function(c){var a=EventDispatcher(c);a.room=void 0;a.elementID=void 0;a.hasAudio=function(){return c.audio};a.hasVideo=function(){return c.video};a.init=function(){try{navigator.webkitGetUserMedia({video:c.video,audio:c.audio},function(b){L.Logger.info("User has granted access to local media.");a.stream=Stream({streamID:0,stream:b});void 0!==c.elementID&&(b=new VideoPlayer({id:a.stream.streamID,stream:a.stream.stream,elementID:c.elementID}),a.player=b);b=PublisherEvent({type:"access-accepted"});
a.dispatchEvent(b)},function(a){L.Logger.error("Failed to get access to local media. Error code was "+a.code+".")}),L.Logger.debug("Requested access to local media")}catch(b){L.Logger.error("Error accessing to local media")}};return a};var Room=function(c){var a=EventDispatcher(c),b,d,e,g;a.streams={};a.roomID="";a.socket={};a.state=0;a.addEventListener("room-disconnected",function(b){var d;a.state=0;for(d in a.streams)a.streams.hasOwnProperty(d)&&(b=a.streams[d],g(b),delete a.streams[d],b=StreamEvent({type:"stream-removed",stream:b}),a.dispatchEvent(b));a.streams={};c.publisher.pc.close();c.publisher.pc=void 0;try{a.socket.disconnect()}catch(e){L.Logger.debug("Socket already disconnected")}a.socket=void 0});g=function(a){void 0!==
a.stream&&(a.player.destroy(),a.pc.close())};b=function(b,c,e){a.socket=io.connect(b.host,{reconnect:!1});a.socket.on("onAddStream",function(b){var c=Stream({streamID:b});a.streams[b]=c;b=StreamEvent({type:"stream-added",stream:c});a.dispatchEvent(b)});a.socket.on("onRemoveStream",function(b){var c=a.streams[b];delete a.streams[b];g(c);b=StreamEvent({type:"stream-removed",stream:c});a.dispatchEvent(b)});a.socket.on("disconnect",function(){L.Logger.info("Socket disconnected");var b=RoomEvent({type:"room-disconnected"});
a.dispatchEvent(b)});d("token",b,c,e)};d=function(b,c,d,e){a.socket.emit(b,c,function(a,b){"success"===a?void 0!==d&&d(b):void 0!==e&&e(b)})};e=function(b,c,d,e){a.socket.emit(b,c,d,function(a,b){e(a,b)})};a.connect=function(){0!==a.state&&L.Logger.error("Room already connected");var d=L.Base64.decodeBase64(c.token);a.state=1;b(JSON.parse(d),function(b){var c=0,d=[],f,e;f=b.streams;e=b.id;a.state=0;for(c in f)f.hasOwnProperty(c)&&(b=Stream({streamID:f[c],stream:void 0}),d.push(b),a.streams[f[c]]=
b);a.roomID=e;L.Logger.info("Connected to room "+a.roomID);c=RoomEvent({type:"room-connected",streams:d});a.dispatchEvent(c)},function(a){L.Logger.error("Not Connected! Error: "+a)})};a.disconnect=function(){var b=RoomEvent({type:"room-disconnected"});a.dispatchEvent(b)};a.publish=function(b){c.publisher=b;b.room=a;b.pc=new RoapConnection("STUN stun.l.google.com:19302",function(a){e("publish","offer",a,function(a,c){b.pc.onsignalingmessage=function(a){b.pc.onsignalingmessage=function(){};e("publish",
"ok",a);L.Logger.info("Stream published "+a);b.stream.streamID=c};b.pc.processSignalingMessage(a)})});b.pc.addStream(b.stream.stream)};a.unpublish=function(){d("unpublish",void 0)};a.subscribe=function(a,b){a.elementID=b;a.pc=new RoapConnection("STUN stun.l.google.com:19302",function(b){e("subscribe",a.streamID,b,function(b){a.pc.processSignalingMessage(b)})});a.pc.onaddstream=function(c){L.Logger.info("Stream subscribed");a.stream=c.stream;c=new VideoPlayer({id:a.streamID,stream:a.stream,elementID:b});
a.player=c};L.Logger.info("Subscribing to: "+a.streamID)};a.unsubscribe=function(b){void 0!==a.socket?d("unsubscribe",b.streamID,function(){g(b)},function(){L.Logger.error("Error calling unsubscribe.")}):callback()};return a};var L=L||{};
L.Logger=function(c){return{DEBUG:0,TRACE:1,INFO:2,WARNING:3,ERROR:4,NONE:5,enableLogPanel:function(){c.Logger.panel=document.createElement("textarea");c.Logger.panel.setAttribute("id","lynckia-logs");c.Logger.panel.setAttribute("style","width: 100%; height: 100%; display: none");c.Logger.panel.setAttribute("rows",20);c.Logger.panel.setAttribute("cols",20);c.Logger.panel.setAttribute("readOnly",!0);document.body.appendChild(c.Logger.panel)},setLogLevel:function(a){a>c.Logger.NONE?a=c.Logger.NONE:a<
c.Logger.DEBUG&&(a=c.Logger.DEBUG);c.Logger.logLevel=a},log:function(a,b){var d="";a<c.Logger.logLevel||(a===c.Logger.DEBUG?d+="DEBUG":a===c.Logger.TRACE?d+="TRACE":a===c.Logger.INFO?d+="INFO":a===c.Logger.WARNING?d+="WARNING":a===c.Logger.ERROR&&(d+="ERROR"),d=d+": "+b,void 0!==c.Logger.panel?c.Logger.panel.value=c.Logger.panel.value+"\n"+d:console.log(d))},debug:function(a){c.Logger.log(c.Logger.DEBUG,a)},trace:function(a){c.Logger.log(c.Logger.TRACE,a)},info:function(a){c.Logger.log(c.Logger.INFO,
a)},warning:function(a){c.Logger.log(c.Logger.WARNING,a)},error:function(a){c.Logger.log(c.Logger.ERROR,a)}}}(L);L=L||{};
L.Base64=function(){var c,a,b,d,e,g,f,h,k;c="A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9,+,/".split(",");a=[];for(e=0;e<c.length;e+=1)a[c[e]]=e;g=function(a){b=a;d=0};f=function(){var a;if(!b||d>=b.length)return-1;a=b.charCodeAt(d)&255;d+=1;return a};h=function(){if(!b)return-1;for(;;){if(d>=b.length)return-1;var c=b.charAt(d);d+=1;if(a[c])return a[c];if("A"===c)return 0}};k=function(a){a=a.toString(16);1===a.length&&(a=
"0"+a);return unescape("%"+a)};return{encodeBase64:function(a){var b,d,e;g(a);a="";b=Array(3);d=0;for(e=!1;!e&&-1!==(b[0]=f());)if(b[1]=f(),b[2]=f(),a+=c[b[0]>>2],-1!==b[1]?(a+=c[b[0]<<4&48|b[1]>>4],-1!==b[2]?(a+=c[b[1]<<2&60|b[2]>>6],a+=c[b[2]&63]):(a+=c[b[1]<<2&60],a+="=",e=!0)):(a+=c[b[0]<<4&48],a+="=",a+="=",e=!0),d+=4,76<=d)a+="\n",d=0;return a},decodeBase64:function(a){var b,c;g(a);a="";b=Array(4);for(c=!1;!c&&-1!==(b[0]=h())&&-1!==(b[1]=h());)b[2]=h(),b[3]=h(),a+=k(b[0]<<2&255|b[1]>>4),-1!==
b[2]?(a+=k(b[1]<<4&255|b[2]>>2),-1!==b[3]?a+=k(b[2]<<6&255|b[3]):c=!0):c=!0;return a}}}(L);var View=function(){var c=EventDispatcher({});c.url="http://chotis2.dit.upm.es/erizo";return c};var VideoPlayer=function(c){var a=View({});window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(a,c,e){document.getElementById(c).value=unescape(e)});a.destroy=function(){a.video.pause();a.parentNode.removeChild(a.div)};a.id=c.id;a.stream=c.stream;a.elementID=c.elementID;L.Logger.debug("Creating URL from stream "+a.stream);a.url=webkitURL.createObjectURL(a.stream);a.div=document.createElement("div");a.div.setAttribute("id","player_"+a.id);a.div.setAttribute("style","width: 100%; height: 100%; position: relative; background-color: black");
a.loader=document.createElement("img");a.loader.setAttribute("style","width: 16px; height: 16px; position: absolute; top: 50%; left: 50%; margin-top: -8px; margin-left: -8px");a.loader.setAttribute("id","back_"+a.id);a.loader.setAttribute("src",a.url+"/assets/loader.gif");a.video=document.createElement("video");a.video.setAttribute("id","stream"+a.id);a.video.setAttribute("style","width: 100%; height: 100%; position: absolute");a.video.setAttribute("autoplay","autoplay");void 0!==a.elementID?document.getElementById(a.elementID).appendChild(a.div):
document.body.appendChild(a.div);a.parentNode=a.div.parentNode;a.div.appendChild(a.loader);a.div.appendChild(a.video);a.bar=new Bar({elementID:"player_"+a.id,id:a.id,video:a.video});a.div.onmouseover=function(){a.bar.display()};a.div.onmouseout=function(){a.bar.hide()};a.video.src=a.url;return a};var Bar=function(c){var a=View({});a.elementID=c.elementID;a.id=c.id;var b=void 0;a.div=document.createElement("div");a.div.setAttribute("id","bar_"+a.id);a.bar=document.createElement("div");a.bar.setAttribute("style","width: 100%; height: 32px; position: absolute; bottom: 0; right: 0; background-color: rgba(255,255,255,0.62)");a.bar.setAttribute("id","subbar_"+a.id);a.logo=document.createElement("img");a.logo.setAttribute("style","width: 32px; height: 32px; position: absolute; top: 0; left: 0;");
a.logo.setAttribute("src",a.url+"/assets/star.svg");var d=function(c){"block"!==c?c="none":clearTimeout(b);a.div.setAttribute("style","width: 100%; height: 100%; position: relative; bottom: 0; right: 0; display:"+c)};a.display=function(){d("block")};a.hide=function(){b=setTimeout(d,1E3)};console.log(a.elementID);document.getElementById(a.elementID).appendChild(a.div);a.div.appendChild(a.bar);a.bar.appendChild(a.logo);a.speaker=new Speaker({elementID:"bar_"+a.id,id:a.id,video:c.video});a.display();
a.hide();return a};var Speaker=function(c){var a=View({});a.elementID=c.elementID;a.video=c.video;a.id=c.id;a.div=document.createElement("div");a.div.setAttribute("style","width: 32px; height: 32px; position: absolute; bottom: 0; right: 0;");a.icon=document.createElement("img");a.icon.setAttribute("id","volume_"+a.id);a.icon.setAttribute("src",a.url+"/assets/mute48.png");a.icon.setAttribute("style","width: 32px; height: 32px; position: absolute;");a.div.appendChild(a.icon);a.picker=document.createElement("input");a.picker.setAttribute("id",
"picker_"+a.id);a.picker.type="range";a.picker.min=0;a.picker.max=100;a.picker.step=10;a.picker.value=50;a.div.appendChild(a.picker);a.video=a.picker.value;a.picker.oninput=function(){0<a.picker.value?a.icon.setAttribute("src",a.url+"/assets/sound48.png"):a.icon.setAttribute("src",a.url+"/assets/mute48.png");a.video=a.picker.value};var b=function(b){a.picker.setAttribute("style","width: 32px; height: 100px; position: absolute; bottom: 30px; right: 0px; -webkit-appearance: slider-vertical; display: "+
b)};b("none");a.div.onmouseover=function(){b("block")};a.div.onmouseout=function(){b("none")};document.getElementById(a.elementID).appendChild(a.div);return a};
