/*
*/
var XMLHttpRequest = require("./../vendor/xmlhttprequest").XMLHttpRequest;
var CryptoJS=CryptoJS||function(d,g){var h={},a=h.lib={},c=a.Base=function(){function e(){}return{extend:function(b){e.prototype=this;var a=new e;b&&a.mixIn(b);a.$super=this;return a},create:function(){var e=this.extend();e.init.apply(e,arguments);return e},init:function(){},mixIn:function(e){for(var b in e)e.hasOwnProperty(b)&&(this[b]=e[b]);e.hasOwnProperty("toString")&&(this.toString=e.toString)},clone:function(){return this.$super.extend(this)}}}(),n=a.WordArray=c.extend({init:function(e,b){e=
this.words=e||[];this.sigBytes=b!=g?b:4*e.length},toString:function(e){return(e||i).stringify(this)},concat:function(e){var b=this.words,a=e.words,f=this.sigBytes,e=e.sigBytes;this.clamp();if(f%4)for(var c=0;c<e;c++)b[f+c>>>2]|=(a[c>>>2]>>>24-8*(c%4)&255)<<24-8*((f+c)%4);else if(65535<a.length)for(c=0;c<e;c+=4)b[f+c>>>2]=a[c>>>2];else b.push.apply(b,a);this.sigBytes+=e;return this},clamp:function(){var e=this.words,b=this.sigBytes;e[b>>>2]&=4294967295<<32-8*(b%4);e.length=d.ceil(b/4)},clone:function(){var e=
c.clone.call(this);e.words=this.words.slice(0);return e},random:function(e){for(var b=[],a=0;a<e;a+=4)b.push(4294967296*d.random()|0);return n.create(b,e)}}),l=h.enc={},i=l.Hex={stringify:function(e){for(var b=e.words,e=e.sigBytes,a=[],f=0;f<e;f++){var c=b[f>>>2]>>>24-8*(f%4)&255;a.push((c>>>4).toString(16));a.push((c&15).toString(16))}return a.join("")},parse:function(e){for(var b=e.length,a=[],f=0;f<b;f+=2)a[f>>>3]|=parseInt(e.substr(f,2),16)<<24-4*(f%8);return n.create(a,b/2)}},m=l.Latin1={stringify:function(b){for(var a=
b.words,b=b.sigBytes,f=[],c=0;c<b;c++)f.push(String.fromCharCode(a[c>>>2]>>>24-8*(c%4)&255));return f.join("")},parse:function(b){for(var a=b.length,f=[],c=0;c<a;c++)f[c>>>2]|=(b.charCodeAt(c)&255)<<24-8*(c%4);return n.create(f,a)}},b=l.Utf8={stringify:function(b){try{return decodeURIComponent(escape(m.stringify(b)))}catch(a){throw Error("Malformed UTF-8 data");}},parse:function(b){return m.parse(unescape(encodeURIComponent(b)))}},f=a.BufferedBlockAlgorithm=c.extend({reset:function(){this._data=n.create();
this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=b.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(b){var a=this._data,f=a.words,c=a.sigBytes,i=this.blockSize,h=c/(4*i),h=b?d.ceil(h):d.max((h|0)-this._minBufferSize,0),b=h*i,c=d.min(4*b,c);if(b){for(var g=0;g<b;g+=i)this._doProcessBlock(f,g);g=f.splice(0,b);a.sigBytes-=c}return n.create(g,c)},clone:function(){var b=c.clone.call(this);b._data=this._data.clone();return b},_minBufferSize:0});a.Hasher=f.extend({init:function(){this.reset()},
reset:function(){f.reset.call(this);this._doReset()},update:function(b){this._append(b);this._process();return this},finalize:function(b){b&&this._append(b);this._doFinalize();return this._hash},clone:function(){var b=f.clone.call(this);b._hash=this._hash.clone();return b},blockSize:16,_createHelper:function(b){return function(a,f){return b.create(f).finalize(a)}},_createHmacHelper:function(b){return function(a,f){return p.HMAC.create(b,f).finalize(a)}}});var p=h.algo={};return h}(Math);
(function(){var d=CryptoJS,g=d.lib,h=g.WordArray,g=g.Hasher,a=[],c=d.algo.SHA1=g.extend({_doReset:function(){this._hash=h.create([1732584193,4023233417,2562383102,271733878,3285377520])},_doProcessBlock:function(c,d){for(var i=this._hash.words,g=i[0],b=i[1],f=i[2],h=i[3],e=i[4],j=0;80>j;j++){if(16>j)a[j]=c[d+j]|0;else{var k=a[j-3]^a[j-8]^a[j-14]^a[j-16];a[j]=k<<1|k>>>31}k=(g<<5|g>>>27)+e+a[j];k=20>j?k+((b&f|~b&h)+1518500249):40>j?k+((b^f^h)+1859775393):60>j?k+((b&f|b&h|f&h)-1894007588):k+((b^f^h)-
899497514);e=h;h=f;f=b<<30|b>>>2;b=g;g=k}i[0]=i[0]+g|0;i[1]=i[1]+b|0;i[2]=i[2]+f|0;i[3]=i[3]+h|0;i[4]=i[4]+e|0},_doFinalize:function(){var a=this._data,c=a.words,h=8*this._nDataBytes,d=8*a.sigBytes;c[d>>>5]|=128<<24-d%32;c[(d+64>>>9<<4)+15]=h;a.sigBytes=4*c.length;this._process()}});d.SHA1=g._createHelper(c);d.HmacSHA1=g._createHmacHelper(c)})();
(function(){var d=CryptoJS,g=d.enc.Utf8;d.algo.HMAC=d.lib.Base.extend({init:function(d,a){d=this._hasher=d.create();"string"==typeof a&&(a=g.parse(a));var c=d.blockSize,n=4*c;a.sigBytes>n&&(a=d.finalize(a));for(var l=this._oKey=a.clone(),i=this._iKey=a.clone(),m=l.words,b=i.words,f=0;f<c;f++)m[f]^=1549556828,b[f]^=909522486;l.sigBytes=i.sigBytes=n;this.reset()},reset:function(){var d=this._hasher;d.reset();d.update(this._iKey)},update:function(d){this._hasher.update(d);return this},finalize:function(d){var a=
this._hasher,d=a.finalize(d);a.reset();return a.finalize(this._oKey.clone().concat(d))}})})();var N=N||{};N.authors=["aalonsog@dit.upm.es","prodriguez@dit.upm.es","jcervino@dit.upm.es"];N.version=0.1;N=N||{};
N.Base64=function(){var d,g,h,a,c,n,l,i,m;d="A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9,+,/".split(",");g=[];for(c=0;c<d.length;c+=1)g[d[c]]=c;n=function(b){h=b;a=0};l=function(){var b;if(!h||a>=h.length)return-1;b=h.charCodeAt(a)&255;a+=1;return b};i=function(){if(!h)return-1;for(;;){if(a>=h.length)return-1;var b=h.charAt(a);a+=1;if(g[b])return g[b];if("A"===b)return 0}};m=function(b){b=b.toString(16);1===b.length&&(b=
"0"+b);return unescape("%"+b)};return{encodeBase64:function(b){var a,c,e;n(b);b="";a=Array(3);c=0;for(e=!1;!e&&-1!==(a[0]=l());)if(a[1]=l(),a[2]=l(),b+=d[a[0]>>2],-1!==a[1]?(b+=d[a[0]<<4&48|a[1]>>4],-1!==a[2]?(b+=d[a[1]<<2&60|a[2]>>6],b+=d[a[2]&63]):(b+=d[a[1]<<2&60],b+="=",e=!0)):(b+=d[a[0]<<4&48],b+="=",b+="=",e=!0),c+=4,76<=c)b+="\n",c=0;return b},decodeBase64:function(b){var a,c;n(b);b="";a=Array(4);for(c=!1;!c&&-1!==(a[0]=i())&&-1!==(a[1]=i());)a[2]=i(),a[3]=i(),b+=m(a[0]<<2&255|a[1]>>4),-1!==
a[2]?(b+=m(a[1]<<4&255|a[2]>>2),-1!==a[3]?b+=m(a[2]<<6&255|a[3]):c=!0):c=!0;return b}}}(N);N=N||{};
N.API=function(d){var g,h;g=function(a,c,g,l,i,m){var b,f,p,e,j,k,o;b=d.API.params.service;f=d.API.params.key;""===b||""===f?console.log("ServiceID and Key are required!!"):(p=(new Date).getTime(),e=Math.floor(99999*Math.random()),j=p+","+e,k="MAuth realm=http://marte3.dit.upm.es,mauth_signature_method=HMAC_SHA1",""!==i&&""!==m&&(k=k+",mauth_username="+i+",mauth_role="+m,j+=","+i+","+m),i=h(j,f),k=k+",mauth_serviceid="+b+",mauth_cnonce="+e+",mauth_timestamp="+p+",mauth_signature="+i,o=new XMLHttpRequest,o.onreadystatechange=
function(){o.readyState===4&&a(o.responseText)},o.open(c,l,!0),o.setRequestHeader("Authorization",k),o.setRequestHeader("Content-Type","application/json"),o.send(JSON.stringify(g)))};h=function(a,c){var g;g=CryptoJS.HmacSHA1(a,c).toString(CryptoJS.enc.Hex);return d.Base64.encodeBase64(g)};return{params:{service:void 0,key:void 0},url:"http://chotis2.dit.upm.es:3000/",init:function(a,c){d.API.params.service=a;d.API.params.key=c},createRoom:function(a,c){g(c,"POST",{name:a},d.API.url+"rooms")},getRooms:function(a){g(a,
"GET",void 0,d.API.url+"rooms")},getRoom:function(a,c){g(c,"GET",void 0,d.API.url+"rooms/"+a)},deleteRoom:function(a,c){g(c,"DELETE",void 0,d.API.url+"rooms/"+a)},createToken:function(a,c,h,l){g(l,"POST",void 0,d.API.url+"rooms/"+a+"/tokens",c,h)},createService:function(a,c,h){g(h,"POST",{name:a,key:c},d.API.url+"services/")},getServices:function(a){g(a,"GET",void 0,d.API.url+"services/")},getService:function(a,c){g(c,"GET",void 0,d.API.url+"services/"+a)},deleteService:function(a,c){g(c,"DELETE",
void 0,d.API.url+"services/"+a)},getUsers:function(a,c){g(c,"GET",void 0,d.API.url+"rooms/"+a+"/users/")},getUser:function(a,c,h){g(h,"GET",void 0,d.API.url+"rooms/"+a+"/users/"+c)},deleteUser:function(a,c,h){g(h,"DELETE",void 0,d.API.url+"rooms/"+a+"/users/"+c)}}}(N);
module.exports = N;
