

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findapr-util.cmake")
# Global approach
set(apr-util_FOUND 1)
set(apr-util_VERSION "1.6.1")

find_package_handle_standard_args(apr-util REQUIRED_VARS
                                  apr-util_VERSION VERSION_VAR apr-util_VERSION)
mark_as_advanced(apr-util_FOUND apr-util_VERSION)


set(apr-util_INCLUDE_DIRS "/home/carlos/.conan/data/apr-util/1.6.1/_/_/package/4082b01864e36b6836702e9b4b27e6c9e7334619/include")
set(apr-util_INCLUDE_DIR "/home/carlos/.conan/data/apr-util/1.6.1/_/_/package/4082b01864e36b6836702e9b4b27e6c9e7334619/include")
set(apr-util_INCLUDES "/home/carlos/.conan/data/apr-util/1.6.1/_/_/package/4082b01864e36b6836702e9b4b27e6c9e7334619/include")
set(apr-util_RES_DIRS )
set(apr-util_DEFINITIONS "-DAPU_DECLARE_STATIC")
set(apr-util_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(apr-util_COMPILE_DEFINITIONS "APU_DECLARE_STATIC")
set(apr-util_COMPILE_OPTIONS_LIST "" "")
set(apr-util_COMPILE_OPTIONS_C "")
set(apr-util_COMPILE_OPTIONS_CXX "")
set(apr-util_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(apr-util_LIBRARIES "") # Will be filled later
set(apr-util_LIBS "") # Same as apr-util_LIBRARIES
set(apr-util_SYSTEM_LIBS dl pthread rt)
set(apr-util_FRAMEWORK_DIRS )
set(apr-util_FRAMEWORKS )
set(apr-util_FRAMEWORKS_FOUND "") # Will be filled later
set(apr-util_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(apr-util_FRAMEWORKS_FOUND "${apr-util_FRAMEWORKS}" "${apr-util_FRAMEWORK_DIRS}")

mark_as_advanced(apr-util_INCLUDE_DIRS
                 apr-util_INCLUDE_DIR
                 apr-util_INCLUDES
                 apr-util_DEFINITIONS
                 apr-util_LINKER_FLAGS_LIST
                 apr-util_COMPILE_DEFINITIONS
                 apr-util_COMPILE_OPTIONS_LIST
                 apr-util_LIBRARIES
                 apr-util_LIBS
                 apr-util_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to apr-util_LIBS and apr-util_LIBRARY_LIST
set(apr-util_LIBRARY_LIST aprutil-1)
set(apr-util_LIB_DIRS "/home/carlos/.conan/data/apr-util/1.6.1/_/_/package/4082b01864e36b6836702e9b4b27e6c9e7334619/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_apr-util_DEPENDENCIES "${apr-util_FRAMEWORKS_FOUND} ${apr-util_SYSTEM_LIBS} apr::apr;Iconv::Iconv;EXPAT::EXPAT")

conan_package_library_targets("${apr-util_LIBRARY_LIST}"  # libraries
                              "${apr-util_LIB_DIRS}"      # package_libdir
                              "${_apr-util_DEPENDENCIES}"  # deps
                              apr-util_LIBRARIES            # out_libraries
                              apr-util_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "apr-util")                                      # package_name

set(apr-util_LIBS ${apr-util_LIBRARIES})

foreach(_FRAMEWORK ${apr-util_FRAMEWORKS_FOUND})
    list(APPEND apr-util_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND apr-util_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${apr-util_SYSTEM_LIBS})
    list(APPEND apr-util_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND apr-util_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(apr-util_LIBRARIES_TARGETS "${apr-util_LIBRARIES_TARGETS};apr::apr;Iconv::Iconv;EXPAT::EXPAT")
set(apr-util_LIBRARIES "${apr-util_LIBRARIES};apr::apr;Iconv::Iconv;EXPAT::EXPAT")

set(CMAKE_MODULE_PATH "/home/carlos/.conan/data/apr-util/1.6.1/_/_/package/4082b01864e36b6836702e9b4b27e6c9e7334619/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/carlos/.conan/data/apr-util/1.6.1/_/_/package/4082b01864e36b6836702e9b4b27e6c9e7334619/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET apr-util::apr-util)
        add_library(apr-util::apr-util INTERFACE IMPORTED)
        if(apr-util_INCLUDE_DIRS)
            set_target_properties(apr-util::apr-util PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${apr-util_INCLUDE_DIRS}")
        endif()
        set_property(TARGET apr-util::apr-util PROPERTY INTERFACE_LINK_LIBRARIES
                     "${apr-util_LIBRARIES_TARGETS};${apr-util_LINKER_FLAGS_LIST}")
        set_property(TARGET apr-util::apr-util PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${apr-util_COMPILE_DEFINITIONS})
        set_property(TARGET apr-util::apr-util PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${apr-util_COMPILE_OPTIONS_LIST}")
        
        # Library dependencies
        include(CMakeFindDependencyMacro)

        if(NOT apr_FOUND)
            find_dependency(apr REQUIRED)
        else()
            message(STATUS "Dependency apr already found")
        endif()


        if(NOT Iconv_FOUND)
            find_dependency(Iconv REQUIRED)
        else()
            message(STATUS "Dependency Iconv already found")
        endif()


        if(NOT EXPAT_FOUND)
            find_dependency(EXPAT REQUIRED)
        else()
            message(STATUS "Dependency EXPAT already found")
        endif()

    endif()
endif()

foreach(_BUILD_MODULE_PATH ${apr-util_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
