

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated FindEXPAT.cmake")
# Global approach
set(EXPAT_FOUND 1)
set(EXPAT_VERSION "2.4.1")

find_package_handle_standard_args(EXPAT REQUIRED_VARS
                                  EXPAT_VERSION VERSION_VAR EXPAT_VERSION)
mark_as_advanced(EXPAT_FOUND EXPAT_VERSION)


set(EXPAT_INCLUDE_DIRS "/home/carlos/.conan/data/expat/2.4.1/_/_/package/d2aa7fde96817bd9d6d001c15e0479bf82133afe/include")
set(EXPAT_INCLUDE_DIR "/home/carlos/.conan/data/expat/2.4.1/_/_/package/d2aa7fde96817bd9d6d001c15e0479bf82133afe/include")
set(EXPAT_INCLUDES "/home/carlos/.conan/data/expat/2.4.1/_/_/package/d2aa7fde96817bd9d6d001c15e0479bf82133afe/include")
set(EXPAT_RES_DIRS )
set(EXPAT_DEFINITIONS "-DXML_STATIC")
set(EXPAT_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(EXPAT_COMPILE_DEFINITIONS "XML_STATIC")
set(EXPAT_COMPILE_OPTIONS_LIST "" "")
set(EXPAT_COMPILE_OPTIONS_C "")
set(EXPAT_COMPILE_OPTIONS_CXX "")
set(EXPAT_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(EXPAT_LIBRARIES "") # Will be filled later
set(EXPAT_LIBS "") # Same as EXPAT_LIBRARIES
set(EXPAT_SYSTEM_LIBS )
set(EXPAT_FRAMEWORK_DIRS )
set(EXPAT_FRAMEWORKS )
set(EXPAT_FRAMEWORKS_FOUND "") # Will be filled later
set(EXPAT_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(EXPAT_FRAMEWORKS_FOUND "${EXPAT_FRAMEWORKS}" "${EXPAT_FRAMEWORK_DIRS}")

mark_as_advanced(EXPAT_INCLUDE_DIRS
                 EXPAT_INCLUDE_DIR
                 EXPAT_INCLUDES
                 EXPAT_DEFINITIONS
                 EXPAT_LINKER_FLAGS_LIST
                 EXPAT_COMPILE_DEFINITIONS
                 EXPAT_COMPILE_OPTIONS_LIST
                 EXPAT_LIBRARIES
                 EXPAT_LIBS
                 EXPAT_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to EXPAT_LIBS and EXPAT_LIBRARY_LIST
set(EXPAT_LIBRARY_LIST expat)
set(EXPAT_LIB_DIRS "/home/carlos/.conan/data/expat/2.4.1/_/_/package/d2aa7fde96817bd9d6d001c15e0479bf82133afe/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_EXPAT_DEPENDENCIES "${EXPAT_FRAMEWORKS_FOUND} ${EXPAT_SYSTEM_LIBS} ")

conan_package_library_targets("${EXPAT_LIBRARY_LIST}"  # libraries
                              "${EXPAT_LIB_DIRS}"      # package_libdir
                              "${_EXPAT_DEPENDENCIES}"  # deps
                              EXPAT_LIBRARIES            # out_libraries
                              EXPAT_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "EXPAT")                                      # package_name

set(EXPAT_LIBS ${EXPAT_LIBRARIES})

foreach(_FRAMEWORK ${EXPAT_FRAMEWORKS_FOUND})
    list(APPEND EXPAT_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND EXPAT_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${EXPAT_SYSTEM_LIBS})
    list(APPEND EXPAT_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND EXPAT_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(EXPAT_LIBRARIES_TARGETS "${EXPAT_LIBRARIES_TARGETS};")
set(EXPAT_LIBRARIES "${EXPAT_LIBRARIES};")

set(CMAKE_MODULE_PATH "/home/carlos/.conan/data/expat/2.4.1/_/_/package/d2aa7fde96817bd9d6d001c15e0479bf82133afe/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/carlos/.conan/data/expat/2.4.1/_/_/package/d2aa7fde96817bd9d6d001c15e0479bf82133afe/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET EXPAT::EXPAT)
        add_library(EXPAT::EXPAT INTERFACE IMPORTED)
        if(EXPAT_INCLUDE_DIRS)
            set_target_properties(EXPAT::EXPAT PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${EXPAT_INCLUDE_DIRS}")
        endif()
        set_property(TARGET EXPAT::EXPAT PROPERTY INTERFACE_LINK_LIBRARIES
                     "${EXPAT_LIBRARIES_TARGETS};${EXPAT_LINKER_FLAGS_LIST}")
        set_property(TARGET EXPAT::EXPAT PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${EXPAT_COMPILE_DEFINITIONS})
        set_property(TARGET EXPAT::EXPAT PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${EXPAT_COMPILE_OPTIONS_LIST}")
        
    endif()
endif()

foreach(_BUILD_MODULE_PATH ${EXPAT_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
