

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findapr.cmake")
# Global approach
set(apr_FOUND 1)
set(apr_VERSION "1.7.0")

find_package_handle_standard_args(apr REQUIRED_VARS
                                  apr_VERSION VERSION_VAR apr_VERSION)
mark_as_advanced(apr_FOUND apr_VERSION)


set(apr_INCLUDE_DIRS "/home/carlos/.conan/data/apr/1.7.0/_/_/package/f396348b1fa523bdf8023510af23ec5f21afcfb2/include")
set(apr_INCLUDE_DIR "/home/carlos/.conan/data/apr/1.7.0/_/_/package/f396348b1fa523bdf8023510af23ec5f21afcfb2/include")
set(apr_INCLUDES "/home/carlos/.conan/data/apr/1.7.0/_/_/package/f396348b1fa523bdf8023510af23ec5f21afcfb2/include")
set(apr_RES_DIRS )
set(apr_DEFINITIONS "-DAPR_DECLARE_STATIC")
set(apr_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(apr_COMPILE_DEFINITIONS "APR_DECLARE_STATIC")
set(apr_COMPILE_OPTIONS_LIST "" "")
set(apr_COMPILE_OPTIONS_C "")
set(apr_COMPILE_OPTIONS_CXX "")
set(apr_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(apr_LIBRARIES "") # Will be filled later
set(apr_LIBS "") # Same as apr_LIBRARIES
set(apr_SYSTEM_LIBS dl pthread)
set(apr_FRAMEWORK_DIRS )
set(apr_FRAMEWORKS )
set(apr_FRAMEWORKS_FOUND "") # Will be filled later
set(apr_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(apr_FRAMEWORKS_FOUND "${apr_FRAMEWORKS}" "${apr_FRAMEWORK_DIRS}")

mark_as_advanced(apr_INCLUDE_DIRS
                 apr_INCLUDE_DIR
                 apr_INCLUDES
                 apr_DEFINITIONS
                 apr_LINKER_FLAGS_LIST
                 apr_COMPILE_DEFINITIONS
                 apr_COMPILE_OPTIONS_LIST
                 apr_LIBRARIES
                 apr_LIBS
                 apr_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to apr_LIBS and apr_LIBRARY_LIST
set(apr_LIBRARY_LIST apr-1)
set(apr_LIB_DIRS "/home/carlos/.conan/data/apr/1.7.0/_/_/package/f396348b1fa523bdf8023510af23ec5f21afcfb2/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_apr_DEPENDENCIES "${apr_FRAMEWORKS_FOUND} ${apr_SYSTEM_LIBS} ")

conan_package_library_targets("${apr_LIBRARY_LIST}"  # libraries
                              "${apr_LIB_DIRS}"      # package_libdir
                              "${_apr_DEPENDENCIES}"  # deps
                              apr_LIBRARIES            # out_libraries
                              apr_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "apr")                                      # package_name

set(apr_LIBS ${apr_LIBRARIES})

foreach(_FRAMEWORK ${apr_FRAMEWORKS_FOUND})
    list(APPEND apr_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND apr_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${apr_SYSTEM_LIBS})
    list(APPEND apr_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND apr_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(apr_LIBRARIES_TARGETS "${apr_LIBRARIES_TARGETS};")
set(apr_LIBRARIES "${apr_LIBRARIES};")

set(CMAKE_MODULE_PATH "/home/carlos/.conan/data/apr/1.7.0/_/_/package/f396348b1fa523bdf8023510af23ec5f21afcfb2/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/carlos/.conan/data/apr/1.7.0/_/_/package/f396348b1fa523bdf8023510af23ec5f21afcfb2/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET apr::apr)
        add_library(apr::apr INTERFACE IMPORTED)
        if(apr_INCLUDE_DIRS)
            set_target_properties(apr::apr PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${apr_INCLUDE_DIRS}")
        endif()
        set_property(TARGET apr::apr PROPERTY INTERFACE_LINK_LIBRARIES
                     "${apr_LIBRARIES_TARGETS};${apr_LINKER_FLAGS_LIST}")
        set_property(TARGET apr::apr PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${apr_COMPILE_DEFINITIONS})
        set_property(TARGET apr::apr PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${apr_COMPILE_OPTIONS_LIST}")
        
    endif()
endif()

foreach(_BUILD_MODULE_PATH ${apr_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
