var CryptoJS=CryptoJS||function(c,f){var g={},b=g.lib={},e=function(){},l=b.Base={extend:function(d){e.prototype=this;var a=new e;d&&a.mixIn(d);a.$super=this;return a},create:function(){var d=this.extend();d.init.apply(d,arguments);return d},init:function(){},mixIn:function(d){for(var a in d)d.hasOwnProperty(a)&&(this[a]=d[a]);d.hasOwnProperty("toString")&&(this.toString=d.toString)},clone:function(){return this.$super.extend(this)}},k=b.WordArray=l.extend({init:function(d,a){d=this.words=d||[];this.sigBytes=
a!=f?a:4*d.length},toString:function(d){return(d||m).stringify(this)},concat:function(d){var a=this.words,b=d.words,i=this.sigBytes,d=d.sigBytes;this.clamp();if(i%4)for(var c=0;c<d;c++)a[i+c>>>2]|=(b[c>>>2]>>>24-8*(c%4)&255)<<24-8*((i+c)%4);else if(65535<b.length)for(c=0;c<d;c+=4)a[i+c>>>2]=b[c>>>2];else a.push.apply(a,b);this.sigBytes+=d;return this},clamp:function(){var d=this.words,a=this.sigBytes;d[a>>>2]&=4294967295<<32-8*(a%4);d.length=c.ceil(a/4)},clone:function(){var d=l.clone.call(this);
d.words=this.words.slice(0);return d},random:function(d){for(var a=[],b=0;b<d;b+=4)a.push(4294967296*c.random()|0);return k.create(a,d)}}),h=g.enc={},m=h.Hex={stringify:function(d){for(var a=d.words,d=d.sigBytes,b=[],c=0;c<d;c++){var i=a[c>>>2]>>>24-8*(c%4)&255;b.push((i>>>4).toString(16));b.push((i&15).toString(16))}return b.join("")},parse:function(d){for(var a=d.length,b=[],c=0;c<a;c+=2)b[c>>>3]|=parseInt(d.substr(c,2),16)<<24-4*(c%8);return k.create(b,a/2)}},a=h.Latin1={stringify:function(d){for(var a=
d.words,d=d.sigBytes,b=[],c=0;c<d;c++)b.push(String.fromCharCode(a[c>>>2]>>>24-8*(c%4)&255));return b.join("")},parse:function(d){for(var a=d.length,b=[],c=0;c<a;c++)b[c>>>2]|=(d.charCodeAt(c)&255)<<24-8*(c%4);return k.create(b,a)}},i=h.Utf8={stringify:function(d){try{return decodeURIComponent(escape(a.stringify(d)))}catch(b){throw Error("Malformed UTF-8 data");}},parse:function(d){return a.parse(unescape(encodeURIComponent(d)))}},o=b.BufferedBlockAlgorithm=l.extend({reset:function(){this._data=k.create();
this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=i.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(a){var b=this._data,i=b.words,e=b.sigBytes,h=this.blockSize,l=e/(4*h),l=a?c.ceil(l):c.max((l|0)-this._minBufferSize,0),a=l*h,e=c.min(4*a,e);if(a){for(var g=0;g<a;g+=h)this._doProcessBlock(i,g);g=i.splice(0,a);b.sigBytes-=e}return k.create(g,e)},clone:function(){var a=l.clone.call(this);a._data=this._data.clone();return a},_minBufferSize:0});b.Hasher=o.extend({init:function(){this.reset()},
reset:function(){o.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);this._doFinalize();return this._hash},clone:function(){var a=o.clone.call(this);a._hash=this._hash.clone();return a},blockSize:16,_createHelper:function(a){return function(b,c){return a.create(c).finalize(b)}},_createHmacHelper:function(a){return function(b,c){return n.HMAC.create(a,c).finalize(b)}}});var n=g.algo={};return g}(Math);
(function(){var c=CryptoJS,f=c.lib,g=f.WordArray,f=f.Hasher,b=[],e=c.algo.SHA1=f.extend({_doReset:function(){this._hash=g.create([1732584193,4023233417,2562383102,271733878,3285377520])},_doProcessBlock:function(c,e){for(var h=this._hash.words,g=h[0],a=h[1],i=h[2],f=h[3],n=h[4],d=0;80>d;d++){if(16>d)b[d]=c[e+d]|0;else{var j=b[d-3]^b[d-8]^b[d-14]^b[d-16];b[d]=j<<1|j>>>31}j=(g<<5|g>>>27)+n+b[d];j=20>d?j+((a&i|~a&f)+1518500249):40>d?j+((a^i^f)+1859775393):60>d?j+((a&i|a&f|i&f)-1894007588):j+((a^i^f)-
899497514);n=f;f=i;i=a<<30|a>>>2;a=g;g=j}h[0]=h[0]+g|0;h[1]=h[1]+a|0;h[2]=h[2]+i|0;h[3]=h[3]+f|0;h[4]=h[4]+n|0},_doFinalize:function(){var b=this._data,c=b.words,e=8*this._nDataBytes,g=8*b.sigBytes;c[g>>>5]|=128<<24-g%32;c[(g+64>>>9<<4)+15]=e;b.sigBytes=4*c.length;this._process()}});c.SHA1=f._createHelper(e);c.HmacSHA1=f._createHmacHelper(e)})();
(function(){var c=CryptoJS,f=c.enc.Utf8;c.algo.HMAC=c.lib.Base.extend({init:function(c,b){c=this._hasher=c.create();"string"==typeof b&&(b=f.parse(b));var e=c.blockSize,l=4*e;b.sigBytes>l&&(b=c.finalize(b));for(var k=this._oKey=b.clone(),h=this._iKey=b.clone(),m=k.words,a=h.words,i=0;i<e;i++)m[i]^=1549556828,a[i]^=909522486;k.sigBytes=h.sigBytes=l;this.reset()},reset:function(){var c=this._hasher;c.reset();c.update(this._iKey)},update:function(c){this._hasher.update(c);return this},finalize:function(c){var b=
this._hasher,c=b.finalize(c);b.reset();return b.finalize(this._oKey.clone().concat(c))}})})();var N=N||{};N.authors=["aalonsog@dit.upm.es","prodriguez@dit.upm.es","jcervino@dit.upm.es"];N.version=0.1;N=N||{};
N.Base64=function(){var c,f,g,b,e,l,k,h,m;c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".split("");f=[];for(e=0;e<c.length;e+=1)f[c[e]]=e;l=function(a){g=a;b=0};k=function(){var a;if(!g||b>=g.length)return-1;a=g.charCodeAt(b)&255;b+=1;return a};h=function(){if(!g)return-1;for(;!(b>=g.length);){var a=g.charAt(b);b+=1;if(f[a])return f[a];if("A"===a)return 0}return-1};m=function(a){a=a.toString(16);1===a.length&&(a="0"+a);return unescape("%"+a)};return{encodeBase64:function(a){var b,
e,h;l(a);a="";b=Array(3);e=0;for(h=!1;!h&&-1!==(b[0]=k());)if(b[1]=k(),b[2]=k(),a+=c[b[0]>>2],-1!==b[1]?(a+=c[b[0]<<4&48|b[1]>>4],-1!==b[2]?(a+=c[b[1]<<2&60|b[2]>>6],a+=c[b[2]&63]):(a+=c[b[1]<<2&60],a+="=",h=!0)):(a+=c[b[0]<<4&48],a+="=",a+="=",h=!0),e+=4,76<=e)a+="\n",e=0;return a},decodeBase64:function(a){var b,c;l(a);a="";b=Array(4);for(c=!1;!c&&-1!==(b[0]=h())&&-1!==(b[1]=h());)b[2]=h(),b[3]=h(),a+=m(b[0]<<2&255|b[1]>>4),-1!==b[2]?(a+=m(b[1]<<4&255|b[2]>>2),-1!==b[3]?a+=m(b[2]<<6&255|b[3]):c=
!0):c=!0;return a}}}(N);N=N||{};
N.API=function(c){var f,g;f=function(b,e,f,k,h,m){var a,i,o,n,d,j;a=c.API.params.service;i=c.API.params.key;""===a||""===i?console.log("ServiceID and Key are required!!"):(o=(new Date).getTime(),n=o+",123123aaff",d="MAuth realm=http://marte3.dit.upm.es,mauth_signature_method=HMAC_SHA1",""!==h&&""!==m&&(d=d+",mauth_username="+h+",mauth_role="+m,n+=","+h+","+m),h=g(n,i),d=d+",mauth_serviceid="+a+",mauth_cnonce=123123aaff,mauth_timestamp="+o+",mauth_signature="+h,j=new XMLHttpRequest,j.onreadystatechange=
function(){j.readyState===4&&b(j.responseText)},j.open(e,k,!0),j.setRequestHeader("Authorization",d),j.setRequestHeader("Content-Type","application/json"),console.log("Sending "+e+" to "+k),j.send(JSON.stringify(f)))};g=function(b,e){var f;f=CryptoJS.HmacSHA1(b,e).toString(CryptoJS.enc.Hex);return c.Base64.encodeBase64(f)};return{params:{url:void 0,service:void 0,key:void 0},init:function(b,e,f){c.API.params.url=b;c.API.params.service=e;c.API.params.key=f},createRoom:function(b,e){f(e,"POST",b,c.API.params.url+
"rooms")},getRooms:function(b){f(b,"GET",void 0,c.API.params.url+"rooms")},deleteRoom:function(b,e){f(e,"DELETE",void 0,c.API.params.url+"rooms/"+b)},createToken:function(b,e,g,k){f(k,"POST",void 0,c.API.params.url+"rooms/"+b+"/tokens",e,g)},createService:function(b,e,g){f(g,"POST",{name:b,key:e},c.API.params.url+"services/")},getServices:function(b){f(b,"GET",void 0,c.API.params.url+"services/")},getService:function(b,e){f(e,"GET",void 0,c.API.params.url+"services/"+b)},deleteService:function(b,
e){f(e,"DELETE",void 0,c.API.params.url+"services/"+b)},getUsers:function(b,e){f(e,"GET",void 0,c.API.params.url+"rooms/"+b+"/users/")},getUser:function(b,e,g){f(g,"GET",void 0,c.API.params.url+"rooms/"+b+"/users/"+e)},deleteUser:function(b,e,g){f(g,"DELETE",void 0,c.API.params.url+"rooms/"+b+"/users/"+e)}}}(N);